schema_version = "1.0.0"
id = "rotor"
version = "1.1.1"
name = "rotor"
tagline = "rotor"
maintainer = "ezelar.com"
type = "add-on"


# Optional link to documentation, support, source files, etc
# website = "https://github.com/niewinny/rotor"


tags = ["Modeling", "3D View", "Mesh"]
blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]
